//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MriyaGallery.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MriyaGallery.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Елементи галереї.
        /// </summary>
        internal static string PropertiesCaption {
            get {
                return ResourceManager.GetString("PropertiesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати елемент.
        /// </summary>
        internal static string PropertiesCaptionAddItem {
            get {
                return ResourceManager.GetString("PropertiesCaptionAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Велике зображення.
        /// </summary>
        internal static string PropertiesCaptionBigImage {
            get {
                return ResourceManager.GetString("PropertiesCaptionBigImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити елемент.
        /// </summary>
        internal static string PropertiesCaptionDeleteItem {
            get {
                return ResourceManager.GetString("PropertiesCaptionDeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опис.
        /// </summary>
        internal static string PropertiesCaptionDescription {
            get {
                return ResourceManager.GetString("PropertiesCaptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маленьке зображення.
        /// </summary>
        internal static string PropertiesCaptionSmallImage {
            get {
                return ResourceManager.GetString("PropertiesCaptionSmallImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відео.
        /// </summary>
        internal static string PropertiesCaptionVideo {
            get {
                return ResourceManager.GetString("PropertiesCaptionVideo", resourceCulture);
            }
        }
    }
}
