//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MriyaStaffWebparts.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MriyaStaffWebparts.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистити.
        /// </summary>
        internal static string textButtonClearSearch {
            get {
                return ResourceManager.GetString("textButtonClearSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрити.
        /// </summary>
        internal static string textButtonCloseDetails {
            get {
                return ResourceManager.GetString("textButtonCloseDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сховати.
        /// </summary>
        internal static string textButtonHide {
            get {
                return ResourceManager.GetString("textButtonHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оновити.
        /// </summary>
        internal static string textButtonRefresh {
            get {
                return ResourceManager.GetString("textButtonRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показати всі.
        /// </summary>
        internal static string textButtonShowAll {
            get {
                return ResourceManager.GetString("textButtonShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Місто.
        /// </summary>
        internal static string textCity {
            get {
                return ResourceManager.GetString("textCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберить місто зі списку.
        /// </summary>
        internal static string textCityHint {
            get {
                return ResourceManager.GetString("textCityHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підрозділ.
        /// </summary>
        internal static string textDepartment {
            get {
                return ResourceManager.GetString("textDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберить підрозділ зі списку.
        /// </summary>
        internal static string textDepartmentHint {
            get {
                return ResourceManager.GetString("textDepartmentHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наступна.
        /// </summary>
        internal static string textFooterNext {
            get {
                return ResourceManager.GetString("textFooterNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попередня.
        /// </summary>
        internal static string textFooterPrevious {
            get {
                return ResourceManager.GetString("textFooterPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Місто.
        /// </summary>
        internal static string textHeaderCity {
            get {
                return ResourceManager.GetString("textHeaderCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підрозділ.
        /// </summary>
        internal static string textHeaderDepartment {
            get {
                return ResourceManager.GetString("textHeaderDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата народження.
        /// </summary>
        internal static string textHeaderDob {
            get {
                return ResourceManager.GetString("textHeaderDob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        internal static string textHeaderEmail {
            get {
                return ResourceManager.GetString("textHeaderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я.
        /// </summary>
        internal static string textHeaderFirstName {
            get {
                return ResourceManager.GetString("textHeaderFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підрозділ, Посада.
        /// </summary>
        internal static string textHeaderJob {
            get {
                return ResourceManager.GetString("textHeaderJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посада.
        /// </summary>
        internal static string textHeaderJobTitle {
            get {
                return ResourceManager.GetString("textHeaderJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прізвіще.
        /// </summary>
        internal static string textHeaderLastName {
            get {
                return ResourceManager.GetString("textHeaderLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По батькові.
        /// </summary>
        internal static string textHeaderMiddleName {
            get {
                return ResourceManager.GetString("textHeaderMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПІБ.
        /// </summary>
        internal static string textHeaderName {
            get {
                return ResourceManager.GetString("textHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тел моб.
        /// </summary>
        internal static string textHeaderPhoneMobile {
            get {
                return ResourceManager.GetString("textHeaderPhoneMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        internal static string textHeaderPhones {
            get {
                return ResourceManager.GetString("textHeaderPhones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тел р..
        /// </summary>
        internal static string textHeaderPhoneWork {
            get {
                return ResourceManager.GetString("textHeaderPhoneWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фото.
        /// </summary>
        internal static string textHeaderPhoto {
            get {
                return ResourceManager.GetString("textHeaderPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Записи не знайдено.
        /// </summary>
        internal static string textNoRecordsFound {
            get {
                return ResourceManager.GetString("textNoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Знайдено {0} записів....
        /// </summary>
        internal static string textRecorsFound {
            get {
                return ResourceManager.GetString("textRecorsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фільтр.
        /// </summary>
        internal static string textSearchButtonFilterSearch {
            get {
                return ResourceManager.GetString("textSearchButtonFilterSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показати всіх.
        /// </summary>
        internal static string textSearchButtonFilterSearchAlt {
            get {
                return ResourceManager.GetString("textSearchButtonFilterSearchAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошук.
        /// </summary>
        internal static string textSearchButtonLabel {
            get {
                return ResourceManager.GetString("textSearchButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Встановити фільтр.
        /// </summary>
        internal static string textSearchFilterHint {
            get {
                return ResourceManager.GetString("textSearchFilterHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шукати в телефонному довіднику.
        /// </summary>
        internal static string textSearchHint {
            get {
                return ResourceManager.GetString("textSearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошук....
        /// </summary>
        internal static string textSearchLabel {
            get {
                return ResourceManager.GetString("textSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефонна книга.
        /// </summary>
        internal static string textWPCaption {
            get {
                return ResourceManager.GetString("textWPCaption", resourceCulture);
            }
        }
    }
}
