//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MriyaDiscussionDashboard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MriyaDiscussionDashboard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть дошку обговорень для відображення.
        /// </summary>
        internal static string messagePleaseSelectDiscussionBoard {
            get {
                return ResourceManager.GetString("messagePleaseSelectDiscussionBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дошка обговорень не задана.
        /// </summary>
        internal static string textDiscussionBoardUnknown {
            get {
                return ResourceManager.GetString("textDiscussionBoardUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть дошку обговорень.
        /// </summary>
        internal static string textDiscussionSelectionLabel {
            get {
                return ResourceManager.GetString("textDiscussionSelectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На знайдено жодної дошки обговорень.
        /// </summary>
        internal static string textDiscussionSelectionLabelNoDiscussionsFound {
            get {
                return ResourceManager.GetString("textDiscussionSelectionLabelNoDiscussionsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При запиті до дошки оголошень .
        /// </summary>
        internal static string textExceptionQueryingDiscussionBoard {
            get {
                return ResourceManager.GetString("textExceptionQueryingDiscussionBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не вдалося отримати відповіді.
        /// </summary>
        internal static string textExceptionQueryingDiscussionBoardNoReplies {
            get {
                return ResourceManager.GetString("textExceptionQueryingDiscussionBoardNoReplies", resourceCulture);
            }
        }
    }
}
